app:
  version: @project.version@
  name: @project.name@
  description: @project.description@
  ownerName: Sunny Srivastava

config:
  encodingScheme: pbkdf2

---
spring:
  profiles: default
server:
  port: 8002

---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: multi-encoder
